// components/wood/LocaleHead.tsx
// The single generator of every page's document head (SEO-02/04/06/07, D-07).
// No page hand-writes an SEO tag: canonical, the reciprocal hreflang set, the
// default-locale fallback link and the paired og:locale values are all derived
// here from lib/routeMap.ts and lib/locale.ts.
//
// Why one component rather than a <Head> per page: an hreflang set is only
// honoured if it is reciprocal, and Google discards a non-reciprocal set
// wholesale with no build error to catch it. Generating both sides of every
// pair from counterpartPath() — whose involution is proven by test in
// lib/routeMap.test.ts — makes reciprocity a property of one tested function
// instead of eighteen hand-written blocks that must agree by inspection.
//
// Locale tag strings are never spelled literally in this file. HTML_LANG holds
// the IETF tags for hreflang and OG_LOCALE holds the underscore-separated
// OpenGraph codes; the two must never be swapped, which is exactly why
// lib/locale.ts keeps them as separate records.
//
// lib/routeMap.ts is a pure lookup table with no filesystem access, so it is
// safe here. The server-only project data module is not, and is not imported.
import React from "react";
import Head from "next/head";
import { HTML_LANG, OG_LOCALE } from "../../lib/locale";
import type { Locale } from "../../lib/locale";
import { wordmark } from "../../lib/portfolio";
import { counterpartPath } from "../../lib/routeMap";
import { SITE_ORIGIN } from "../../lib/site";

/* ── Helpers ──────────────────────────────────────────────────────────── */

/**
 * The site-wide fallback share card, and the ONLY image whose dimensions this
 * component knows for certain — it is committed build output generated by
 * scripts/generate-og-image.ts at exactly this size.
 *
 * `alt` is English-only and locale-invariant BECAUSE THE IMAGE IS. The card
 * rasterizes English text (D-1), so an English alt describes it accurately;
 * this is not a translation gap to be filled later. Localized share images —
 * and with them a localized alt — are out of scope this milestone, which is
 * also why `ogImage` below is not locale-branched.
 *
 * The alt must repeat, verbatim, the two lines the card actually rasterizes:
 * WORDMARK and SPECIALISMS in scripts/generate-og-image.ts. Nothing enforces
 * that, and it has already drifted once — the alt kept an older "MLOps,
 * Applied ML, Scalable Cloud Systems" positioning long after the card itself
 * said "Backend, DevOps, Cloud System", so screen-reader users were given a
 * description of an image that no longer existed. Change one, change both.
 */
export const DEFAULT_OG_IMAGE = {
  path: "/images/og-default.png",
  width: 1200,
  height: 630,
  alt: "Chun-Ju (Iridium) Tao — Backend, DevOps, Cloud System",
} as const;

// The other member of the two-locale union. A lookup rather than a ternary so
// adding a third locale becomes a type error here instead of a silent wrong
// pairing.
const OTHER_LOCALE: Record<Locale, Locale> = {
  en: "zh",
  zh: "en",
};

// Absolute URL from a site-root-relative path. Both canonical and OpenGraph
// require absolute URLs, and SITE_ORIGIN is the canonical host — deliberately
// not the github.io one, which only redirects to it.
const absolute = (path: string): string => `${SITE_ORIGIN}${path}`;

/* ── Component ────────────────────────────────────────────────────────── */

export default function LocaleHead({
  locale,
  title,
  description,
  path,
  ogType = "website",
  ogImage = DEFAULT_OG_IMAGE.path,
  ogImageAlt,
}: {
  locale: Locale;
  /** Rendered as the sole text child of <title>. */
  title: string;
  description: string;
  /**
   * This page's own route in its own locale — leading-slash and, except the
   * 404 route, trailing-slash terminated (next.config.js sets trailingSlash).
   * Always a value produced by lib/routeMap.ts, never composed free-hand.
   */
  path: string;
  ogType?: "website" | "article";
  /**
   * Site-root-relative image path; made absolute here. Defaults to the site
   * share card, so HomePage, ResumePage and NotFoundPage inherit an image
   * without passing anything — and without being edited at all.
   */
  ogImage?: string;
  /**
   * Alt text for a CALLER-SUPPLIED ogImage. Omitted deliberately when the
   * caller does not know one: see the og:image:alt tag below.
   */
  ogImageAlt?: string;
}) {
  const canonicalUrl = absolute(path);
  const counterpart = counterpartPath(path);

  // Locale-aware by construction — the English tree gets "Tao", the /zh/ tree
  // gets "歐東" — from the dictionary key the nav and footer already use, so no
  // new string and no new CJK glyph enter the font subset.
  const siteName = wordmark(locale);

  // The ONLY gate on the dimension tags below. A strict comparison against the
  // default's own path, not a truthiness check, so a caller that happens to
  // pass a different image can never inherit the default's measurements.
  const usingDefaultImage = ogImage === DEFAULT_OG_IMAGE.path;

  // An alt only when one is genuinely known: the caller's, or the default
  // image's when that is what we are serving. A custom image with no supplied
  // alt emits NO alt tag — honest silence, not a gap to paper over.
  const resolvedOgImageAlt =
    ogImageAlt ?? (usingDefaultImage ? DEFAULT_OG_IMAGE.alt : null);

  // Which side of the pair is English is decided from `locale`, never by
  // inspecting the strings — the prefix belongs to lib/locale.ts alone.
  const englishUrl =
    counterpart === null
      ? null
      : absolute(locale === "en" ? path : counterpart);
  const chineseUrl =
    counterpart === null
      ? null
      : absolute(locale === "zh" ? path : counterpart);

  return (
    <Head>
      {/* Single text child. An array of children — or a sibling expression
          beside it — exports an EMPTY <title>; this repo shipped that bug once
          already, and here it would recur across every route at once. */}
      <title>{title}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content={description} />

      {/* Self-referencing, in this page's own locale. Exactly one per page;
          no two routes share a canonical URL because lib/routeMap.ts asserts
          its own uniqueness. */}
      <link rel="canonical" href={canonicalUrl} />

      {/* Emitted only when a real counterpart exists. A self-referencing or
          dangling pair is worse than none at all: the whole set is thrown
          away, taking the valid half with it. */}
      {englishUrl !== null && chineseUrl !== null && (
        <>
          <link rel="alternate" hrefLang={HTML_LANG.en} href={englishUrl} />
          <link rel="alternate" hrefLang={HTML_LANG.zh} href={chineseUrl} />
          {/* English is the root locale, so it is also the fallback served to
              any language this site does not publish. */}
          <link rel="alternate" hrefLang="x-default" href={englishUrl} />
        </>
      )}

      <meta property="og:type" content={ogType} />
      <meta property="og:site_name" content={siteName} />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:url" content={canonicalUrl} />

      {/* Unconditional: ogImage always has a value now that it defaults. */}
      <meta property="og:image" content={absolute(ogImage)} />
      {resolvedOgImageAlt !== null && (
        <meta property="og:image:alt" content={resolvedOgImageAlt} />
      )}
      {/* Gated on usingDefaultImage alone, and sourced by stringifying the
          constant rather than by typing 1200/630 a second time. This is
          deliberate: these are the dimensions of the ONE image this component
          measured. A call-site-supplied image has unknown dimensions, and
          declaring a size we never measured would be fabrication in markup —
          the same rule that governs the content files. */}
      {usingDefaultImage && (
        <>
          <meta
            property="og:image:width"
            content={String(DEFAULT_OG_IMAGE.width)}
          />
          <meta
            property="og:image:height"
            content={String(DEFAULT_OG_IMAGE.height)}
          />
        </>
      )}

      {/* Exactly one of each, and never the same value. */}
      <meta property="og:locale" content={OG_LOCALE[locale]} />
      <meta
        property="og:locale:alternate"
        content={OG_LOCALE[OTHER_LOCALE[locale]]}
      />

      {/* Twitter/X uses name=, not property=. summary_large_image is what turns
          a small thumbnail row into a full-width card — without it even the
          project pages, which have always carried an og:image, render small.
          twitter:site and twitter:creator are DELIBERATELY ABSENT: the owner's
          current handle could not be verified, and asserting one would be a
          fabricated claim attributing this site to an account that may not be
          his. Absence is the correct value here, not a TODO. */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={absolute(ogImage)} />
    </Head>
  );
}
