// styles/fonts.ts
// Single font-definitions module (Next's official "font definitions file"
// pattern — see nextjs.org/docs/pages/api-reference/components/font). Both
// next/font loaders are instantiated here exactly once and consumed only by
// pages/_document.page.tsx, which applies their `.variable` classNames directly
// to <Html>. This keeps the project's existing constraint intact: no next/font
// loader function call lives in pages/_document.page.tsx — only the already-
// instantiated `.variable` string constants are imported from this module.
//
// No explicit annotations are needed here: next/font's `localFont` already
// returns a typed `NextFontWithVariable`, so `huninn` and `meslo` (and their
// `.variable` strings) infer correctly under `strict`.
//
// Both faces are `next/font/local` over a committed woff2 subset: there is no
// `next/font/google` loader left in this project, and adding one back would
// reintroduce a build-time fetch of fonts.googleapis.com that the hermetic
// assets/fonts/ sources exist to avoid.
import localFont from "next/font/local";

// Self-hosted display font: CJK-subsetted Open Huninn (SIL OFL 1.1), vendored
// under public/fonts/. Regenerated automatically by scripts/subset-font.ts.
export const huninn = localFont({
  src: "../public/fonts/open-huninn-subset.woff2",
  variable: "--font-huninn",
  display: "swap",
  preload: true,
});

// Self-hosted mono face: subsetted Meslo LG M (Apache 2.0), vendored under
// public/fonts/ and regenerated by the same scripts/subset-font.ts run. It
// replaced JetBrains Mono, which was pulled through next/font/google.
//
// Only 400 and 700 ship. Meslo has no intermediate weights, and nothing in
// styles/globals.css asks the mono family for one; 700 is carried so a bold
// mono element renders the real Bold face instead of a synthesised smear.
// No italic: the only `font-style: italic` rules in globals.css are on the
// sans hero/lede, never on a `var(--font-mono)` surface.
export const meslo = localFont({
  src: [
    {
      path: "../public/fonts/meslo-lgm-regular-subset.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/meslo-lgm-bold-subset.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-meslo",
  display: "swap",
  preload: true,
});
